<?php
/**
 * Created by PhpStorm.
 * User: Florine
 * Date: 24/03/2017
 * Time: 08:47
 */

namespace AppBundle\Repository;
/**
 *
 *
 * CartesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartesRepository extends \Doctrine\ORM\EntityRepository
{
    //http://docs.doctrine-project.org/en/latest/reference/dql-doctrine-query-language.html#using-index-by
    public function getAll()
    {
        return $this->createQueryBuilder('c')
            ->indexBy('c','c.id')
            ->getQuery()
            ->getResult();
    }
}
