<?php

namespace AppBundle\Repository;

/**
 * instrumentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class instrumentsRepository extends \Doctrine\ORM\EntityRepository
{
}
