<?php

namespace AppBundle\Repository;

/**
 * jouerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class jouerRepository extends \Doctrine\ORM\EntityRepository
{
}
