<?php

namespace AppBundle\Repository;

/**
 * partieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class partieRepository extends \Doctrine\ORM\EntityRepository
{
}
