<?php
/**
 * Created by PhpStorm.
 * User: Florine
 * Date: 24/03/2017
 * Time: 08:50
 */
namespace AppBundle\Repository;
/**
 * PartiesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartiesRepository extends \Doctrine\ORM\EntityRepository
{
}