<?php

namespace AppBundle\Repository;

/**
 * situation_de_jeuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class situation_de_jeuRepository extends \Doctrine\ORM\EntityRepository
{
}
